### ISSUE TITLE
Validating xaml input string for FlowDocument

### ISSUE THREAD

**Issue by tstojecki** [cwensley/Portable.Xaml#101]
Hi,
Can we use this library to parse FlowDocument strings?

In a .net framework, we can do this:
`var xamlString = "<FlowDocument xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\" xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\"><Paragraph>Test</Paragraph></FlowDocument>";`

`XamlReader.Parse(xamlString) as FlowDocument;`

When attempting that with Portable.Xaml
`Portable.Xaml.XamlServices.Parse(xamlString);`

I get back an error

_Current operation is valid only when the underlying type on a XamlType is known, but it is unknown for '{http://schemas.microsoft.com/winfx/2006/xaml/presentation}FlowDocument'_

Is this the right use case for this lib? If so, can you give some pointers on how to work with this type of xaml?

**Comment by ewinnington** [comment]
By running on the .Net Framework 4.6.1 and adding a prefix to the FlowDocument as well as a new xmlns, I'm able to go further, but I get Portable.Xaml.XamlObjectWriterException: Type '{clr-namespace:System.Windows.Documents;assembly=PresentationFramework}FlowDocument' does not have a content property.

This seems to lead to [XamlObjectWriter.cs#L450](https://github.com/cwensley/Portable.Xaml/blob/ac0b34cc8951411eed813c16cfb8e3badebe7da5/src/Portable.Xaml/Portable.Xaml/XamlObjectWriter.cs#L450). 

```
using Portable.Xaml;
using System;
using System.Windows.Documents;

//Running on .Net Framework 4.6.1
//Nuget: Portable.Xaml 0.22
//References: PresentationFramework.dll
//References: PresentationCore.dll
//References: WindowsBase.dll

namespace FD.PortableXaml
{
    class Program
    {
        static void Main(string[] args)
        {
            var xamlString = "<a:FlowDocument xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\" xmlns:a=\"clr-namespace:System.Windows.Documents;assembly=PresentationFramework\" xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\"><Paragraph>Test</Paragraph></a:FlowDocument>";

             var fd_sys_xaml = System.Windows.Markup.XamlReader.Parse(xamlString) as FlowDocument;
            Console.WriteLine(fd_sys_xaml.ToString());

            var fd_portable_xaml = Portable.Xaml.XamlServices.Parse(xamlString) as FlowDocument;
            Console.WriteLine(fd_portable_xaml.ToString());
        }
    }
}
```



```
Unhandled Exception: Portable.Xaml.XamlObjectWriterException: Type '{clr-namespace:System.Windows.Documents;assembly=PresentationFramework}FlowDocument' does not have a content property.
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteStartMember(XamlMember property)
   at Portable.Xaml.XamlWriterInternalBase.WriteStartMember(XamlMember property)
   at Portable.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at Portable.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Portable.Xaml.XamlServices.Load(XamlReader xamlReader)
   at Portable.Xaml.XamlServices.Parse(String xaml)
   at FD.PortableXaml.Program.Main
```

**Comment by tstojecki** [comment]
Thanks for you input @ewinnington 
Even if it worked, the example you provide would force me down the full .net framework path and I am in .net core 2.1

I think I might be out of luck as I am not finding much about FlowDocument in xaml schema files. 

I will close it but happy to reopen if there is new input or additional requests for this.

**Comment by ewinnington** [comment]
FlowDocument is not included in Core - to my knowledge. So anyway, you wouldn't be able to instantiate a FlowDocument outside of .net framework.
