### ISSUE TITLE
Add support for System.Collections.Immutable

### ISSUE THREAD

**Issue by wieslawsoltes** [cwensley/Portable.Xaml#11]
Sample model:
https://github.com/wieslawsoltes/XamlDemo/blob/immutable/XamlDemo/Model.cs

Sample Xaml:
https://github.com/wieslawsoltes/XamlDemo/blob/immutable/XamlDemo/Project.caml

**Comment by cwensley** [comment]
nice suggestion!  do you know if System.Xaml supports immutable collections?  I ask as I'm not sure the best way to implement this.  E.g. should we look for the Add() method and if it returns the same collection instance, set it back to the property?  Or is it that it builds up an internal list and creates a new instance of the immutable when setting the property..

Probably a good idea to add some tests to see what it does and try to emulate that somehow.

**Comment by wieslawsoltes** [comment]
`System.Xaml` does not support, at least in my sample it failed.

I have found this solution used in `Newtonsoft.Json`: https://github.com/JamesNK/Newtonsoft.Json/blob/4c256e7afd46197a6e40127f77dff18e8f044b8c/Src/Newtonsoft.Json/Utilities/ImmutableCollectionsUtils.cs

**Comment by cwensley** [comment]
ah ok, that makes it easy then as we can then come up with our own strategy to implement this.  Thanks for the link I'll take a look.

**Comment by wieslawsoltes** [comment]
The `Newtonsoft.Json` works great with `Immutable Collections`.

I've been trying to find solution using built-in Xaml mechanisms from `Portable.Xaml`:
https://github.com/wieslawsoltes/XamlDemo/tree/ImmutableArray/XamlDemo/Xaml

But this is as fat I've got. And this does not work yet whe properties are of `Immutable` type, only when they are `IList<>` and later created as `Immutable`.

**Comment by cwensley** [comment]
Now supported!

**Comment by Mike-EEE** [comment]
I'd just like to say that this thread has totally influenced me and led me to the light of immutable collections.  I am starting to take the dive and require them for my design going forward.  Just thought I would share! :sunglasses:
