### ISSUE TITLE
Portable.Xaml does not support XamlType.IsUsableDuringInitialization

### ISSUE THREAD

**Issue by grokys** [cwensley/Portable.Xaml#110]
This setting is used to notify XAML that a created object should be attached to its parent immediately after construction:

https://docs.microsoft.com/en-us/dotnet/api/system.xaml.xamltype.isusableduringinitialization?view=netframework-4.7.2

WPF uses this, and Avalonia requires it. We currently implement some hacks to make things happen in this order; it would be good to remove them.

**Comment by cm4ker** [comment]
@grokys Hi! I think we are completely close this.
