### ISSUE TITLE
Will this support FixedDocuments and FlowDocuments?

### ISSUE THREAD

**Issue by charlie430** [cwensley/Portable.Xaml#131]
Hi,

I was just wondering if this library will support the ability to create FixedDocuments and FlowDocuments in the System.Windows.Documents namespace? I use those to create XPS files, and would love to be able to create XPS documents in .Net Core, but wasn't sure if the intention of this library would include that.

Thanks,
Charlie

**Comment by cm4ker** [comment]
Hello, @charlie430. Portable.Xaml does not include the System.Windows.Documents namespace.

**Comment by cwensley** [comment]
Yes, those namespaces exist in `PresentationFramework.dll`, which is unfortunately Windows only.  You should be able to [use those with .NET Core 3](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/) though, along with System.Xaml.

This library is a cross platform implementation of System.Xaml only.

**Comment by charlie430** [comment]
@cwensley @cm4ker Okay, thank you for the clarification.
