### ISSUE TITLE
Escaping { and } with \ does not work

### ISSUE THREAD

**Issue by wieslawsoltes** [cwensley/Portable.Xaml#135]
```XAML
<NumericUpDown FormatString="\{0:N2\} °"/>
```
results in:
```
\N2 °
```
cc: @cm4ker

**Comment by cm4ker** [comment]
Some notes: 
For escape characters use the [Escape Sequence](https://docs.microsoft.com/ru-ru/dotnet/framework/xaml-services/escape-sequence-markup-extension).
