### ISSUE TITLE
Just want to put this project here

### ISSUE THREAD

**Issue by aleGuardiola** [cwensley/Portable.Xaml#138]
Hello I am making this library using Portable.Xaml
https://github.com/aleGuardiola/EasyPdf

**Comment by cm4ker** [comment]
Thank you for using Portable.Xaml in you project! I want to close this because this is not a issue and this is not a Portable.Xaml discussion scope. The best place for posting this information is [Awesome Dot net](https://github.com/thangchung/awesome-dotnet-core).
