### ISSUE TITLE
Serialising a DateTime with an offset is truncated

### ISSUE THREAD

**Issue by Benrnz** [cwensley/Portable.Xaml#14]
Dates with an offset (ie to represent a timezone +12:00).
This date is currently truncated as follows:
`2016-02-29T15:50:51.7922645+13:00` 
is serialised as
`2016-02-29T15:50:51.7922645+13:`

This value is not able to be parsed by the Xaml parser during deserialisation.

**Comment by Benrnz** [comment]
I'm experimenting with an adjustment to the regex to match localised DateTime values inside the DateTimeConverter.  My new experimental regex is: 
`(?=[^:])0+$`
This works fine in Javascript based regex testers (like https://regex101.com/) but not inside .Net. 

For example:
`2016-02-29T15:50:51.7922000` (matching 000)
`2016-02-29T15:50:51.7922645+13:00` (not a match)
Using my above experimental regex both the above examples are matched when only the first should be.

I'll keep hunting, but in case someone has some more black magic foo with regex's than I, and would like to be helpful ;-)

Cheers
Ben

**Comment by cwensley** [comment]
I actually ran into this as well as I was trying to update the tests to run in mono (timezone names are completely different in *nix, so "Pacific Standard Time" doesn't work).  

We should actually be able to do this without regex at all.  According to [msdn](https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Roundtrip), the 'o' specifier is equivalent to this custom format: "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK".  Given that 'F' is the same as 'f' but [without trailing zeros](https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx#FFFFFFF_Specifier), we should be able to change the converter to use `theDate.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'FFFFFFFK")` instead.

**Comment by Benrnz** [comment]
Hey,
Yes, definitely that's a better solution.  I've just been experimenting with this and all tests are passing.  I'll put together a PR for this today. Its a shame we can't leverage the standard O date format, but still better than customising the resulting date/time string manually.

Cheers

**Comment by Benrnz** [comment]
BTW- I'll also update the unit test that uses "Pacific Standard Time" to something else to avoid the differences in *nix.

Cheers

**Comment by cwensley** [comment]
@Benrnz sounds great!  thanks for taking care of that.
