### ISSUE TITLE
XamlServices.Save(fileName, object) not existing

### ISSUE THREAD

**Issue by jensbusch** [cwensley/Portable.Xaml#146]
Hi,
  is there a reason that the function with the filename as parameter hasn't been implemented respectively is commented out? In order of porting an existing dotnet application it would be great if that would be available. It seems to be in the code.

**Comment by cwensley** [comment]
I believe it was commented out as .NET Standard 1.0 didn't have any api's to load from a file path.  This shouldn't be a problem for .NET Standard 2.0.

**Comment by cwensley** [comment]
Now fixed with commit 9ebc392.  Thanks again!
