### ISSUE TITLE
Supporting immutable types

### ISSUE THREAD

**Issue by grokys** [cwensley/Portable.Xaml#16]
Currently if a type has no default constructor, it is not usable from XAML. This is a suggestion for an extension to the XAML standard.

(Ok, there's the [x:Arguments](http://stackoverflow.com/questions/1083159/calling-a-parametrized-constructor-from-xaml) directive, but it's ugly as hell and not even supported anywhere)

Immutable types are becoming more and more common, there should be a better way to handle them. For example in [Perspex](https://github.com/Perspex/Perspex), our `SolidColorBrush` is immutable and so it's not creatable from XAML!

I propose a simple way to handle immutable types:

- If trying to create a class with no default constructor, get the available constructors
- Try to match each property defined in XAML to a constructor argument, by name
- Try to convert each property to the argument type
- If we have a constructor we can call, call it!

For example:

    <SolidColorBrush Color="Red"/>

Would call the:

    SolidColorBrush(Color red)

Constructor.

**Comment by cwensley** [comment]
Thanks for submitting the issue!  This is an interesting problem and I agree it'd be nice if Xaml had better support for immutable objects.

In Portable.Xaml, there is currently the facility to do as you propose, but I believe it only works for markup extensions  (e.g.` {SolidColorBrush Color=Red}` would actually work).  This same functionality could possibly be extended to work for objects as you propose, and use the same `ConstructorArgumentAttribute` to specify what properties should be considered as constructor parameters. 

That being said, it might be a bit of work to get this going as it'll have to defer creation of the object, and if you have any properties defined before it is created that are not part of the constructor, it will have to apply it after all properties are read.  Also, it would probably make sense to support things like this:

```
<SolidColorBrush>
  <SolidColorBrush.Color>Red</SolidColorBrush.Color>
</SolidColorBrush>
```

However, you'd pretty much have to read the entire graph of the object before construction..  which would be hard to make efficient.

**Comment by grokys** [comment]
Hmm, interesting that you mention markup extensions and `ConstructorArgumentAttribute`. What are the differences between markup extensions and this that would cause problems other than the fact that markup extensions don't accept `<Class.Attribute>` properties as you mentioned?

**Comment by cwensley** [comment]
Well, nothing really..  From what I can see, markup extensions are translated from xml to nodes very similarly to any other object, it is just a different syntax (e.g. it does `StartObject`, `StartMember`, `EndMember`, etc. just as if it were expressed as a tag) .  I'd have to check to see why markup extensions are so special in this regard because it honestly doesn't make sense why the same logic can't apply here.

**Comment by cwensley** [comment]
Ok, I lied.  Looking into this further, markup extensions only work with non-default constructors when you use positional parameters (even with System.Xaml).   E.g. `{SolidColorBrush Red}` would work, but `{SolidColorBrush Color=Red}` does not.  You can specify more than one parameter with commas.  Basically, positional parameters specified this way is the same as using `<x:Arguments>`.

**Comment by cwensley** [comment]
Thanks for suggesting the enhancement, @grokys!  Portable.Xaml now supports immutable types this way without using x:Arguments (although it is still supported).

I've added a bunch of tests which should cover most of the cases, including using optional parameters.  Note that you must add the `ConstructorArgumentAttribute` to any property that is used as a constructor parameter, which ties in quite nicely when serializing the object.  It will currently use x:Arguments when serializing, but can be further enhanced as well.

It was surprisingly easy to add this feature without adding much overhead as most of the information was being captured anyway, it just deferred the setting of the members until the object was created.  

Some notes on the implementation:
- In the case of multiple constructors, it will attempt to find the constructor with the most matched parameters.
- A parameter with a default value will not need to be specified nor require a property with the `ConstructorArgument` (though supports one if it is).
- If any (read-only) property that is flagged as a `ConstructorArgument` is set that doesn't match a constructor, a `XamlObjectWriterException` will be thrown
- Any collection properties will require that all constructor arguments be supplied first, in the case of using non-immutable types without default constructors.
- If the type has a default constructor, it will not change any behaviour and act normally.

**Comment by grokys** [comment]
Wow @cwensley, this is *HUGE*! :)

This would be so useful for Perspex where we make reasonable use of immutable types. I need to try giving Portable.Xaml a try with it! Unfortunately that probably won't happen this week, but maybe I can give it a try next week.

Thanks for this!
