### ISSUE TITLE
Deferred loading not yet implemented?

### ISSUE THREAD

**Issue by grokys** [cwensley/Portable.Xaml#17]
I notice the following:

https://github.com/cwensley/Portable.Xaml/blob/master/src/Portable.Xaml/Portable.Xaml/XamlMember.cs#L335

Does this mean deferred loading is not yet supported?

**Comment by cwensley** [comment]
I guess not (;

I'm not even sure what API would be used to load the deferred content..  it appears at first glance that this is some internal magic that isn't actually exposed even with System.Xaml. The 'restrictions' mentioned [here](https://msdn.microsoft.com/en-us/library/windows/apps/mt204785.aspx) say it doesn't work with 'loose' xaml via `XamlReader.Load()`.

**Comment by grokys** [comment]
Ah, I don't need the advanced deferred loading introduced in UWP, just the type used to implement templates etc. The API for that is pretty simple - you can see an example here that works with System.Xaml.

https://github.com/grokys/Avalonia/blob/master/Avalonia/FrameworkTemplate.cs#L21

**Comment by cwensley** [comment]
Ah, thanks for the info - I'm not very familiar with how to work with deferred loading in xaml.  It appears that it mainly operates through `XamlNodeList`, which is also [woefully incomplete](https://github.com/cwensley/Portable.Xaml/blob/master/src/Portable.Xaml/Portable.Xaml/XamlNodeList.cs#L32).

**Comment by grokys** [comment]
Indeed! I was looking into Portable.Xaml to see if it would be better than OmniXaml for Perspex's needs, but without support for deferred loaders we wouldn't even have templates, so that's a no-go ;)

I'll keep my eye on developments here though!

**Comment by cwensley** [comment]
Thanks, and yeah I figured you were kicking the tires for that reason.  I appreciate you submitting the issues, it'll help get Portable.Xaml up to snuff.

**Comment by Michael-DST** [comment]
So sad that Xaml2009 is still not supported :(  Interestingly enough, Xamarin.Xaml supports it, but it is closed-source/internal.  So, that doesn't help us much here.

Btw @grokys, an issue you might be interested in: https://github.com/dotnet/corefx/issues/5766

Please feel free to subscribe/participate.  It would be great/ideal to get everyone on the same (Xaml) page, if possible. :smile:

**Comment by Michael-DST** [comment]
Egads... caffeine hasn't kicked in yet.  My 2009 reference was actually for https://github.com/cwensley/Portable.Xaml/issues/16 ... everything else holds for this thread (and that one, too actually haha).

**Comment by cwensley** [comment]
@Michael-DST as far as I can tell, Portable.Xaml does support a lot of features of Xaml 2009 already (`x:Arguments`, `x:FactoryMethod`, `x:Reference`, common types like `x:String`, etc)

**Comment by Michael-DST** [comment]
Sweet.  Looking forward to diving into it. :)

**Comment by cwensley** [comment]
@grokys so I have this pretty much implemented, but I can't for the life of me see what the `XamlDeferLoadAttribute.ContentType` is actually used for, in my testing it doesn't matter what it is set to in System.Xaml, the behaviour is always the same.

Do you happen to have an idea of how the ContentType of XamlDeferLoad is actually used?  Is it ever going to be different than the type of the property the attribute is declared on?

**Comment by grokys** [comment]
Sorry, no I don't - it's a long time since I implemented deferred loading using System.Xaml and I'm not sure I even understood it then! ;)

**Comment by cwensley** [comment]
@grokys thanks.  From my testing, it doesn't appear to actually do anything when saving or loading so I'll just leave it at that.

I've added tests that now pass on both System.Xaml and Portable.Xaml that should cover the common cases and verify the behaviour, so that should hopefully be sufficient.

Thanks again for reporting the issue!
