### ISSUE TITLE
Supporting libraries that don't know anything about XAML.

### ISSUE THREAD

**Issue by grokys** [cwensley/Portable.Xaml#18]
Currently certain things can only be achieved in XAML with attributes, such as describing the `Content` property. It would be nice if there were a mechanism for discovering these things _without_ using attributes, so that XAML support could be added to libraries that were not written with XAML in mind.

Maybe an `IAttributeService` could be injected into the reader so that this sort of behavior could be configured?

_Note: In reality this is prompted by the fact that in Perspex we want the possibility for XAML to be "just another markup language", but it may be useful elsewhere._

**Comment by Mike-EEE** [comment]
Hahaha... Just another markup langauge?!  MarkupExtensions make it anything _but_ that. :wink: However, I am all for decoupling attributes from consumer implementation. :+1:

**Comment by cwensley** [comment]
Yeah I couldn't agree more that it should be much easier to use Xaml with existing libraries without taking a dependency on it.  

The existing mechanism for doing this by subclassing `XamlType` and overriding methods like `LookupContentProperty`, `LookupAliasedProperty`, etc. can be onerous to implement. I've done this for Eto.Forms [here](https://github.com/picoe/Eto/blob/develop/Source/Eto.Serialization.Xaml/EtoXamlType.cs#L228), which works well but could be better.  _Note: this code does some caching which will no longer be needed with any Lookup* methods_.

The service will need to be injected with the `XamlSchemaContext`, since it does all the caching of the `XamlType` and `XamlMember` instances which will need the service.

Also it'd be nice if there was a better way to override/extend the type converter system as well, since that would be another likely task when integrating with existing libraries.

**Comment by grokys** [comment]
Ah, so it is already possible? I didn't know that. Even if it's rather onerous to implement, it's good to know ;)

**Comment by cwensley** [comment]
@grokys yes, you can pretty much override any behaviour by subclassing `XamlType` and `XamlMember`, and overriding the appropriate method(s) in `XamlSchemaContext` to create them.  There are a few [new overridable methods](https://github.com/cwensley/Portable.Xaml/blob/develop/src/Portable.Xaml/Portable.Xaml/XamlSchemaContext.cs#L522-L569) in `XamlSchemaContext` to easily use your own `XamlMember` implementations, and XamlType can be overridden with `XamlSchemaContext.GetXamlType(Type)`

**Comment by amerkoleci** [comment]
Agree, System.Xaml uses the XamlSchemaContext for overriding this behavior and which attribute are mapped as Content, Name etc.

**Comment by grokys** [comment]
I'm trying out Portable.Xaml with Perspex, where we have our own equivalent of `XmlnsDefinitionAttribute`. I've overridden `XamlSchemaContext` and its `GetAllXamlNamespaces` method to do the lookup using our namespace, but the problem is that `XamlType`'s constructor seems to call the `internal string GetXamlNamespace(string clrNamespace)` method, which is failing as we've overriden `GetAllXamlNamespaces`!

I am right in thinking that this part isn't overridable at the moment?

**Comment by cwensley** [comment]
@grokys, Glancing at the API, it doesn't appear that that will be possible.  The `GetAllXamlNamespaces()` alone wouldn't give enough information to map .net namespaces to xaml namespaces and there doesn't appear to be any other overrides that would work.  However, you _can_ add separate `XmlnsDefinitionAttribute` definitions that point to a different assembly using its `AssemblyName` property (I've done this for Eto.Forms).

Perhaps adding a new overridable method to get all `XmlnsDefinitionAttribute` definitions for a particular assembly would work?  Something like:

`protected virtual IEnumerable<XmlnsDefinitionAttribute> GetDefinitionAttributes(Assembly assembly)`

You could then look at whatever attributes you have, and return an enumeration of Portable.Xaml's `XmlnsDefinitionAttribute` objects.

**Comment by grokys** [comment]
We also have a different system for `TypeConverter`s - the documentation mentions that this should be extensible, but I can't see how. Even a `TypeDescriptor.AddDescriptor` method would suffice.

**Comment by cwensley** [comment]
For `TypeConverter`'s , you can do [this](https://github.com/picoe/Eto/blob/develop/Source/Eto.Serialization.Xaml/EtoXamlType.cs#L145).  It might not be too pretty, but it works within the existing api.  You do not need to cache the instance like this code does (Portable.Xaml now caches it outside of this method).

**Comment by grokys** [comment]
> Perhaps adding a new overridable method to get all XmlnsDefinitionAttribute definitions for a particular assembly would work?

Yes, I think something like that should work.

**Comment by grokys** [comment]
Closing this as it's an old discussion and no point keeping it open.
