### ISSUE TITLE
Attached properties

### ISSUE THREAD

**Issue by globeport** [cwensley/Portable.Xaml#24]
Hi, are you able to provide an example of using attached properties?

For example, my object model has type Grid and TextBlock analogous to the Windows.UI.Xaml Grid and TextBlock controls respectively. 

I'd like to be able to parse Row, Column, RowSpan, ColumnSpan attached properties but not sure how these should fit into my object model and whether any configuration is necessary?

How would I parse the following for example:

`<Grid>
<Grid.ColumnDefinitions>
<ColumnDefinition Width="Auto"/>
<ColumnDefinition Width="Auto"/>
</Grid.ColumnDefinitions>
<TextBlock Grid.Column="0"/>
<TextBlock Grid.Column="1"/>
</Grid>`

(At the moment I have Column, Row, RowSpan and ColumSpan properties on the TextBlock and prior to parsing I replace "Grid.Column" with "Column" etc. Not ideal - Id like to be able to handle attached properties properly.)

Thanks,
Stuart

**Comment by grokys** [comment]
Hi, you shouldn't need to parse anything - our XAML parser should handle converting the XAML into objects. Most of the details of this are identical to e.g. WPF/UWP, how familiar are you with those frameworks? For an introduction you could try reading https://msdn.microsoft.com/en-us/library/ms749011(v=vs.100).aspx

**Comment by globeport** [comment]
Sorry I really meant how would your portable XAML parser handle the above? I'm calling the method XamlServices.Load from PCL and using it to instantiate a custom object tree with all classes defined in PCL. Therefore the method wont have access to Windows.UI.XAML (DependecyProperty etc). In that case will it just ignore the attached attributes? Is it possible for me to define custom attached properties in PCL and have the parser process them? I mean are there portable equivelants to DependencyProperty.RegisterAttached etc.

I have to say although I use custom attached properties, I still don't think I've got a clear understanding of how they integrate with the framework hence the confusion. Thanks for your help.

**Comment by grokys** [comment]
Ok, so are you actually using Perspex? Or are you just using OmniXAML to load the XAML?

**Comment by grokys** [comment]
Ok, I believe that if you're not using any framework then attached properties should just be deserialized by calling the static accessor methods.

**Comment by grokys** [comment]
I believe that if you give the XAML parser the following XAML:

    <Foo>
        <Bar.Baz>Qux</Bar.Baz>
    </Foo>

Then it will:

1. Create an instance of the `Foo` class
2. Try to find a `SetBaz` method on the `Bar` class
3. Call `Bar.SetBaz(instance, "Qux")` where instance is the instance created in step 1.

If the `SetBaz` method accepts a type other than a string, then it will try to use a type converter to convert the string to the appropiate type.

**Comment by globeport** [comment]
No no framework, but thanks for the heads up on Perspex and OmniXaml - I need to take a look at them.
Great I was just about to ask where those static methods should be registered. I'll give it a shot. Thankyou.

**Comment by grokys** [comment]
@globeport sorry, I'm an idiot and thought that this issue had been posted to the Perspex repository. Apologies for the confusion,

I've just added a comment that will hopefully explain things a bit better.

**Comment by globeport** [comment]
Great thanks, I'm just testing it out.

**Comment by globeport** [comment]
Works perfectly thanks for your help

**Comment by Mike-EEE** [comment]
Totally had me too @grokys ... I didn't know if there was an announcement or something somewhere that I missed. :smile:

**Comment by cwensley** [comment]
Thanks @grokys for helping out!  (; 

@globeport was your question answered fully, or do you need any further clarification?

**Comment by globeport** [comment]
No, that's all I needed thanks.
