### ISSUE TITLE
Add support for IEnumerable properties

### ISSUE THREAD

**Issue by cwensley** [cwensley/Portable.Xaml#25]
When encountering an `IEnumerable` or `IEnumerable<T>` property, Portable.Xaml could instantiate a `List<T>` if one isn't specified.  This is not supported in System.Xaml, so it would be an extension of its functionality.

**Comment by cwensley** [comment]
Not really a great idea after thinking about it -- you should explicitly specify the type of object to create in xaml.  Otherwise, if you want to add a number of objects that also happen to implement IEnumerable it wouldn't work.

**Comment by Mike-EEE** [comment]
Maybe check for `IList`?  That is, support `IEnumerable` properties, but only if they implement `IList` (or `IEnumerable<>`)
