### ISSUE TITLE
Issue trying to get a TypeConverter to work...

### ISSUE THREAD

**Issue by BradChase2011** [cwensley/Portable.Xaml#31]
So I have a Color struct that I would like to use in xaml as a string.  In my ColorConverter, I only have the option to override the:

public override object ConvertFrom( ITypeDescriptorContext context, CultureInfo culture, object value )

The from string function seems to not be virtual.  That said I have my CanConvertFrom to return true on strings.  I applied the ColorTypeConverter to my color struct yet in xaml it breaks on compiling with:

Error       The TypeConverter for "Color" does not support converting from a string.    

Is there something I am doing wrong or completely missing the boat on?  I am new to this so I could very easily just be completely missing something simple.  My XAML is set to Page and MSBuild:Compile.  Do I need to change this maybe to use Portable.Xaml?  Or maybe some other initialization?

Thanks btw for putting in the time for all of this!

**Comment by BradChase2011** [comment]
I figured it out.  I had to load the xaml manually.  On top of that there were a bunch of other stuff missing that I presume Mono had left in other libraries so I grabbed the latest code and remade the portable xaml library with the other parts put back in.

**Comment by cwensley** [comment]
Thanks for submitting the issue.  I'm closing as you've figured it out.  The MSBuild:Compile option does not work with Portable.Xaml so that makes sense that it didn't work.

**Comment by BradChase2011** [comment]
Thanks for the reply.  I gotta ask though, is there a reason you didn't move the other classes and remove the forms bits from the original code to work with msbuild?  It seems to work just fine for me right now...  I had to build my own bindings and such but that wasn't such a pain.

**Comment by cwensley** [comment]
I'm not sure I follow.. move what other classes and remove what forms bits?

**Comment by BradChase2011** [comment]
I'd have to go back into the code it's been awhile since I peaked at it.  I have it on visual studio team services at the moment.  But there were some direct calls to the forms library inside for specific xamarin forma stuff that needed removed in their latest code to separate them out and they seemed to have classes in other namespaces that I didnt see in your library.  I had to move a couple over to the portable library(my own recreation of it) and change the namespaces to reflect that.  Then I had to recreate the bindings and such to make it all work although I'm sure it is prolly easier to not recreate them, I just found a couple spots I didn't like so much.

**Comment by BradChase2011** [comment]
They still have issues with things like data templates and resource dictionaries that I removed from checking in the readers if I can remember correctly.

**Comment by cwensley** [comment]
Hm, this project is not the same as what's used in Xamarin Forms.  This was derived from mono's  [System.Xaml](https://github.com/mono/mono/tree/master/mcs/class/System.Xaml), so that explains some of the discrepancy you're seeing there.

I'm not opposed to changes to Portable.Xaml to make it more compatible with Xamarin.Forms, but that will have to be done by the community as I'm not focussed on that.

Also, I'm still not really following what changes you are proposing.  It might be just that I am a little slow or the fact that I know nothing of Xamarin Forms' Xaml parser.  I know that the TypeConverter stuff does indeed work for something like a Color struct (I use it in the [Eto.Forms](https://github.com/picoe/Eto) project), so a repro of the problem would help greatly.

**Comment by BradChase2011** [comment]
Ahh I see now.  OK I thought it came from the xamarin repository.  Sorry about that.  It seems they have improved upon it since the straight mono version.  Yea I'm not using it for xamarin forms at all.  I'm using it for my own personal monogame xaml menuing interface so people can just write high performance xaml whether for video games or vr or what not.  But that definitely explains why I saw all the extra code that you didn't.  I wouldn't mind sharing it with you if you want to incorporate the differences or improve what you have if it helps at all.  I just need to spend some time cleaning up and making sure the bare minimum works for other case scenarios.

**Comment by Mike-EEE** [comment]
I personally would would definitely be interested in seeing anything using menus and monogame. :)  Are you familiar with [EmptyKeys](http://emptykeys.com/)?  That's what's on the top of my list as far as xplat menuing goes, whenever I can finally start digging into it.

**Comment by BradChase2011** [comment]
Haha I had no idea that existed!  I can't wait to dig into the code but yea that seems to be almost the exact idea of what I've been building haha.
