### ISSUE TITLE
Eliminate need for xmlns in xaml markup

### ISSUE THREAD

**Issue by cwensley** [cwensley/Portable.Xaml#42]
In the same way the msbuild team has eliminated the need for xmlns declaration(s), it would be nice if xaml had the same ability. 

Of course the default namespaces would still have to defined somewhere, possibly in the XamlXmlReaderSettings

**Comment by Mike-EEE** [comment]
I'm sure if you have checked out [Ammy](http://www.ammyui.com/2017/01/04/ammy-modern-ui-language-for-xaml-platforms/) you have seen that it has done away with a lot of the ceremony, too.  So, this is a well-intended item.  Even so, I'm curious on how you would do this.  Are you saying for the default/common types?  Or all types?  MSBuild isn't POCO based, so it is easy to see how that could be accomplished there.  Here is a different story.

**Comment by cwensley** [comment]
The way I see this working is by specifying the default xmlns mappings in code, vs in the xaml.  Typically, one would have your own code for loading xaml, and it would only work with specific xaml files.  For example, Eto.Forms has `Eto.Serialization.Xaml.XamlReader.Load()`, WPF has `System.Windows.Markup.XamlReader.Load()`, etc.

In this, you'd do something like this:

```c#
object Load(Stream stream)
{
	var readerSettings = new XamlXmlReaderSettings();
	readerSettings.AddNamespace("", "http://mystandardnamespace");
	readerSettings.AddNamespace("x", XamlLanguage.Xaml2006Namespace);

	var context = new XamlSchemaContext();
	var reader = new XamlXmlReader(stream, context, readerSettings);
	var writer = new XamlObjectWriter(context);
	XamlServices.Transform(reader, writer);
	return writer.Result;
}
```

If the Xaml itself defines these namespaces then it would use those, but it would be optional.

**Comment by Mike-EEE** [comment]
Cool... like where you are going with this.  Definitely use namespaces defined in XML as the precedent before code.  If not defined there, then use what is defined in code as you highlight above.  Although... will the XML even read/load if you are using a namespace prefix if it is not defined at the time it is read?  I thought that was a requirement/expectation of `XmlReader`?  Not 100% sure however and I am sure you are. :)

Also, is there a way to tie into [`XmlnsDefinitionAttribute`](https://github.com/cwensley/Portable.Xaml/blob/develop/src/Portable.Xaml/Portable.Xaml.Markup/XmlnsDefinitionAttribute.cs) and [`XmlPrefixAttribute`](https://github.com/cwensley/Portable.Xaml/blob/develop/src/Portable.Xaml/Portable.Xaml.Markup/XmlnsPrefixAttribute.cs) as well?  Maybe make an extension method taking a `Type` object and it will read the attributes from its assembly into the namespace list?  Not sure how they are used currently so thought I'd mention it just to make sure.  Never know. 👼

**Comment by cwensley** [comment]
I guess the functionality will be reliant on how [`XmlParserContext`](https://msdn.microsoft.com/en-us/library/system.xml.xmlparsercontext(v=vs.110).aspx#Anchor_5) works when you specify a `XmlNamespaceManager`, but yeah that's how I'm hoping it would work (namespaces defined in XML taking precedence).  

Tying into defined `XmlnsDefinitionAttribute` of an assembly is also a great idea, I'll think about how that might work.

**Comment by Mike-EEE** [comment]
Haha cool.  I might have just talked myself into a PR heh heh.

**Comment by cwensley** [comment]
aaaannnd done.

Seems to work exactly as you'd expect, which is pretty awesome.  I will absolutely love writing xaml without xmlns definitions everywhere.

**Comment by Mike-EEE** [comment]
WOW!  super fast.  Very very cool.  So no problems with XmlReader then?

**Comment by Mike-EEE** [comment]
Ah I see how you did it.  Very nice. 👍

**Comment by cwensley** [comment]
@Mike-EEE, only problem I ran into is that when you pass an XmlReader to XamlXmlReader, it can't load it as a fragment (which is what is needed to specify the XmlParserContext).  I just read it as text into a StringReader to bypass that, but it is more efficient to use TextReader, Stream, or String (;

Also, subsequently Portable.Xaml is now closer to 2x faster than System.Xaml after this change as I've eliminated the need for a 'wrapper' XmlReader. (;

**Comment by Mike-EEE** [comment]
That's excellent!  Nice work. 🥇

**Comment by cwensley** [comment]
Thanks for the support @Mike-EEE, you're enthusiasm is infectious. 😄
