### ISSUE TITLE
Simple values used with full clr-namespace definition are not resolved

### ISSUE THREAD

**Issue by donandren** [cwensley/Portable.Xaml#48]
example:
```
<Style xmlns='https://github.com/avaloniaui'
        xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'
        xmlns:sys='clr-namespace:System;assembly=mscorlib'>
    <Style.Resources>
        <x:Double x:Key='Double'>10</x:Double>
        <sys:Double x:Key='Double'>10</sys:Double>
    </Style.Resources>
</Style>
```
x:Double type is resolved properly
sys:Double type is not resolved

currently in Avalonia there is a workaround for that:
https://github.com/donandren/Avalonia/blob/portablexaml/src/Markup/Avalonia.Markup.Xaml/PortableXaml/AvaloniaXamlSchemaContext.cs#L106-L129
and it's working fine for now

**Comment by cwensley** [comment]
I can't seem to reproduce this, perhaps there's something else going on?  See #50 for updated tests.

**Comment by cwensley** [comment]
Looking at your code, perhaps you had [this](https://github.com/donandren/Avalonia/blob/portablexaml/src/Markup/Avalonia.Markup.Xaml/PortableXaml/AvaloniaXamlSchemaContext.cs#L23) turned on when testing that..  It wouldn't resolve unless mscorlib was part of the referenced assemblies list.

**Comment by donandren** [comment]
@cwensley you have a point actually i was using referenced assemblies, when i had problems with this. Then commented them, because  was not sure do i need it.

**Comment by cwensley** [comment]
You only would need it if you want to restrict which assemblies you want the xaml to be able to reference.

**Comment by donandren** [comment]
thanks for the info
