### ISSUE TITLE
Invalid Name attribute content when writing xaml

### ISSUE THREAD

**Issue by wieslawsoltes** [cwensley/Portable.Xaml#55]
When writing xaml I get invalid context of the Name attribute, it should be empty but it contains `&quot;&quot;`

Xaml: https://gist.github.com/wieslawsoltes/38b21783d88dba1e0c022599011a9131

**Comment by cwensley** [comment]
Hey thanks for reporting the issue!  I did notice that but didn't know if it was intentional or not.  It appears that Portable.Xaml assumed that it was writing a markup extension when writing an empty string.  Should now be fixed!

**Comment by wieslawsoltes** [comment]
Thanks for quick fix!
