### ISSUE TITLE
Add support for defining default values with the ShouldSerialize and Reset methods

### ISSUE THREAD

**Issue by wieslawsoltes** [cwensley/Portable.Xaml#56]
Seems like its not supported in Portable.Xaml.

I have tested serialization using this pattern with Newtonsoft.Json and it worked.

References:
* http://www.newtonsoft.com/json/help/html/ConditionalProperties.htm
* https://msdn.microsoft.com/en-us/library/53b8022e(v=vs.110).aspx

This cleans-ups xaml and allow convention-based control over serialization in model. 
For example:
* remove empty `ImmutableArray<object>` object definitions (this can't be set to null as its struct)
* remove empty strings like: `Name=""` which causes issues as `Name` needs to be unique when deserializing

**Comment by cwensley** [comment]
Looks like this is supported by System.Xaml so I've now implemented this for Portable.Xaml as well.  It appears to work regardless of the accessibility of the ShouldSerialize method, so even private methods will be used if defined.

**Comment by wieslawsoltes** [comment]
Thanks, working great. Now after this and previous fixes generated Xaml is looking really nice and its human readable, some examples below:
https://gist.github.com/wieslawsoltes/b14a711017a22e83803c373e6a446751
https://gist.github.com/wieslawsoltes/78e8fe12a216bac3009d359908e47269
https://gist.github.com/wieslawsoltes/359af52a524a286f769831ac5c13a680
https://gist.github.com/wieslawsoltes/daebe75f7267cd93bee5ef7d6248cdd8
https://gist.github.com/wieslawsoltes/0743e9b40da96b5fbedc631968cc51bd
https://gist.github.com/wieslawsoltes/fad92e403bcb3fb1f3dfa0324d819a64
