### ISSUE TITLE
Auto-generate Name property value when string is null or white-space for x:Reference's

### ISSUE THREAD

**Issue by wieslawsoltes** [cwensley/Portable.Xaml#59]
When generating Xaml some objects have null or white-space in the Name property (if present) and this cause code like this: https://gist.github.com/wieslawsoltes/b14a711017a22e83803c373e6a446751#file-and_new-xaml-L73, when loading Xaml you will get exception.

One option is to throw exception during xaml writing and let user know that Name is invalid when its object is referenced.

Other option is to auto-generate Name content and use it for Reference.

**Comment by cwensley** [comment]
Hm, interesting problem!  I think how it works right now is it'll do the right thing if it is null, but if it is not null (even empty) it'll use what is specified. I'll have to check to see what System.Xaml does in this case.

Ideally at least when there's two objects with the same name it should probably throw an exception when trying to reference one of them as it'd be ambiguous.  

I would also guess that it'd treat an empty string for a Name as a valid, and you'd have to change your code to either generate a name, or use null as the default value.  Either way, I'll add a test for that to see if it something that needs to be changed.

**Comment by wieslawsoltes** [comment]
I have one object where I have forgot to set `[Name]` attribute for the `Name` property and generated xaml looks like this:
```XAML
<XDatabase x:Name="__ReferenceID0" IdColumnName="Id" Name="Db" xmlns="https://github.com/Core2D" xmlns:sci="clr-namespace:System.Collections.Immutable;assembly=System.Collections.Immutable" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <XDatabase.Columns>
        <sci:ImmutableArray x:TypeArguments="XColumn">
            <XColumn Id="5711cce1-9c34-4831-b879-62eb7242e668" IsVisible="True" Width="NaN">Column0<XColumn.Owner><x:Reference>__ReferenceID0</x:Reference></XColumn.Owner></XColumn>
            <XColumn Id="be3df398-eec5-426f-9c25-bd3ae1795312" IsVisible="True" Width="NaN">Column1<XColumn.Owner><x:Reference>__ReferenceID0</x:Reference></XColumn.Owner></XColumn>
        </sci:ImmutableArray>
    </XDatabase.Columns>
</XDatabase>
```
the `x:Name` is automatically generated. Not sure what logic should be if custom `[Name]` property is used and its white-space or null.

PS. You see that in this case indentation is somewhat broken:
```XAML
<XColumn Id="5711cce1-9c34-4831-b879-62eb7242e668" IsVisible="True" Width="NaN">Column0<XColumn.Owner><x:Reference>__ReferenceID0</x:Reference></XColumn.Owner></XColumn>
```

**Comment by wieslawsoltes** [comment]
Interesting, I have added missing `[Name]` attribute for this object and generated xaml looks like this:
```XAML
<XDatabase IdColumnName="Id" Name="Db" xmlns="https://github.com/Core2D" xmlns:sci="clr-namespace:System.Collections.Immutable;assembly=System.Collections.Immutable" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <XDatabase.Columns>
        <sci:ImmutableArray x:TypeArguments="XColumn">
            <XColumn Id="f6ba20aa-d39c-4ff8-9b3d-bff19f6ae8ab" IsVisible="True" Name="Column0" Width="NaN" Owner="{x:Reference Db}" />
            <XColumn Id="42cda6d2-a53e-4fd3-8efc-a2e1893dc87d" IsVisible="True" Name="Column1" Width="NaN" Owner="{x:Reference Db}" />
        </sci:ImmutableArray>
    </XDatabase.Columns>
</XDatabase>
```
All is ok know, but the `Owner` is referenced as attribute which is how I wanted. This is related with this issue https://github.com/cwensley/Portable.Xaml/issues/60. The other objects `BaseShape` has also `Owner` property but its not serialized as attribute.

**Comment by wieslawsoltes** [comment]
Another thing, when I set `Name` to empty string I get this:
```XAML
<XDatabase IdColumnName="Id" xmlns="https://github.com/Core2D" xmlns:sci="clr-namespace:System.Collections.Immutable;assembly=System.Collections.Immutable" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <XDatabase.Columns>
        <sci:ImmutableArray x:TypeArguments="XColumn">
            <XColumn Id="5711cce1-9c34-4831-b879-62eb7242e668" IsVisible="True" Name="Column0" Width="NaN" Owner="{x:Reference &quot;&quot;}" />
            <XColumn Id="be3df398-eec5-426f-9c25-bd3ae1795312" IsVisible="True" Name="Column1" Width="NaN" Owner="{x:Reference &quot;&quot;}" />
        </sci:ImmutableArray>
    </XDatabase.Columns>
</XDatabase>
```
this is related to this issue https://github.com/cwensley/Portable.Xaml/issues/55. Not sure if in this case `&quot;&quot;` is valid value for `x:Reference`.

**Comment by cwensley** [comment]
Hey @wieslawsoltes, thanks for the notes.

> the x:Name is automatically generated. Not sure what logic should be if custom [Name] property is used and its white-space or null.

It should if you use a `RuntimeNamePropertyAttribute` (or [Name] attribute in your case as I guess you have it mapped).  It looks like it would only generate the name if it is null.  I'm not sure if System.Xaml just checks for null as well, but my guess is that it is the intended behaviour.

> but the Owner is referenced as attribute which is how I wanted

It'll show up as an attribute as long as no property before it needs to be generated as an element.  This is a complex thing as the ordering of properties is _static_, in that it does not change the order of the properties based on the value of those properties.  Basically, anything that has a property value that can be converted to a string comes first so it can be written as attribute.  I'm not sure how easy it'll be to change this and keep it mildly performant, but it's worth a shot.

> Not sure if in this case &quot;&quot; is valid value for x:Reference.

Yes, I believe this is valid in this case.
