### ISSUE TITLE
Infinite double values

### ISSUE THREAD

**Issue by onyultd** [cwensley/Portable.Xaml#6]
Hi thanks for creating this library! Noticed that serializing infinite double values outputs "Infinity" but this causes an exception during deserialization.

Also are there any control attributes implemented? Noticed that applying DefaultValue attributes has no effect on the serialized output.

Thanks,
Stuart

**Comment by cwensley** [comment]
Thanks for the bug report!  The deserialization should handle any double value, so the TypeConverter probably needs updating for that.  It is probably something to do with the culture used to deserialize.

As for the DefaultValueAttribute, it doesn't look like that's used when serializing so it'll need to be implemented.  I've added a separate (issue #7) to track that.
