### ISSUE TITLE
MarkupExtension-like value should be escaped

### ISSUE THREAD

**Issue by pgrho** [cwensley/Portable.Xaml#63]
I am using Portable.Xaml to serializing object that contains `Json` property.
But `XamlServices.Save` outputs invalid XML like that:

```
<SomeType Json="{ key: 1 }" />
```

And this can'be parsed by `XamlServices.Load`.
I think the output should be escaped as such:

```
<SomeType Json="{}{ key: 1 }" />
```

**Comment by cwensley** [comment]
Hey @pgrho, thanks for submitting the issue!  Yes, you are right it should be escaped so it doesn't think it's a markup extension.  Good catch!

**Comment by cwensley** [comment]
Thanks again!  Should now be fixed.

**Comment by pgrho** [comment]
Worked fine! May I ask you to upload to NuGet?

**Comment by cwensley** [comment]
@pgrho it's now on NuGet as v0.17.  Enjoy!
