### ISSUE TITLE
Markup extensions don't seem to need to derive from MarkupExtension

### ISSUE THREAD

**Issue by grokys** [cwensley/Portable.Xaml#65]
As far as I know, in System.Xaml to create a new markup extension you need to derive from the `MarkupExtension` base class. However in Portable.Xaml this doesn't seem to be the case.

For example, if I change [this class](https://github.com/cwensley/Portable.Xaml/blob/d50730ab59aed99cd2f8aeb4975fcc19d23bb54f/src/Test/System.Xaml/TestedTypes.cs#L402) in the tests to *not* derive from `MarkupExtension`, the tests still seem to pass.

**Comment by cwensley** [comment]
Hey @grokys, thanks for the report but I think you have the wrong conclusion on how a 'markup extension' is parsed.  The markup extension syntax can actually apply to any object when reading, but it does affect how it *writes* the xaml.

You can test System.Xaml with the `Portable.Xaml-tests-net_4_5` project.  If I make that change all tests still pass except for the Write_MyExtension tests.

This is the same behaviour that I'm seeing in Portable.Xaml so it actually is behaving consistently here.

**Comment by grokys** [comment]
That doesn't sounds right to me:.iIf I create a new WPF project with a class:

```
namespace WpfApp1
{
    public class Foo
    {
    }
}
```

And then in markup I try to reference that class as a markup extension:

```
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="clr-namespace:WpfApp1">
  <Button Content="{local:Foo}"/>
</Window>
```

I get the error:

```
error MC3048: '{local:Foo}' value is not a valid MarkupExtension expression. Cannot resolve 'Foo' in namespace 'clr-namespace:WpfApp2'. 'Foo' must be a subclass of MarkupExtension. Line 9 Position 11.
```

**Comment by cwensley** [comment]
WPF != System.Xaml afaik..  Have you tried it with System.Xaml?

**Comment by grokys** [comment]
Indeed you are right. Color me amazed! This is obviously something enforced by WPF rather than by System.Xaml then. TIL ;)

**Comment by cwensley** [comment]
I don't think WPF uses System.Xaml when you are compiling, hence some behaviour disparity.  I believe it does use it when parsing Xaml at runtime though.
