### ISSUE TITLE
.NET standard vs PCL api differences

### ISSUE THREAD

**Issue by cwensley** [cwensley/Portable.Xaml#70]
For .NET Standard, I've enabled the use of the built-in TypeConverter.  However, these api's aren't available for the PCL profiles so Portable.Xaml comes with its own TypeConverter implementation.

This poses a problem if you have a PCL library and a .NET Standard (or Full .NET) library in the same solution, if you use any of the API's that are different.

There are a few options here:

1. Remove PCL support
2. Revert the .NET Standard implementation to use the same TypeConverter that the PCL version provides
3. Leave it as-is and let people rip their hair out

I could use some help/guidance from the community on what direction to go here, and if there's any other options I've missed.  

I would like to support PCL if possible for all the people out there still using it (which may be a while as linux support for .NET Standard tooling is still very lacking), and anyone still using/supporting .NET 4.5 since .NET Standard 1.3 requires .NET 4.6+.

**Comment by cwensley** [comment]
Here's an idea, revert .NET Standard to use the Portable.Xaml type converters, but provide a shim so it will also be compatible with standard type converters..

Eventually when PCL is no longer needed/supported, then the built-in type converters could be removed.

**Comment by jkoritzinsky** [comment]
I have an idea for how to solve this.

For PCL, change the namespaces to match the namespaces of the types in .Net Framework and .Net Standard. Then in the .Net Standard build, use type forwarders to forward the type definitions over. Other than the initial build break from changing the namespaces, this provides a simple direction to move forward with new .net standard versions and not prevent PCL support.

**Comment by jkoritzinsky** [comment]
This would also allow you to remove PCL support in the future and not break builds when people switch over to .net standard.

**Comment by cwensley** [comment]
Fixed with #81
