### ISSUE TITLE
Portable.Xaml doesn't recognize property as a collection if it's declared type doesn't look like one

### ISSUE THREAD

**Issue by kekekeks** [cwensley/Portable.Xaml#71]
```cs
class Foo
{
      public object Bars {get; } = new List<Bar>();
}
```

```xaml
<Foo>
  <Foo.Bars>
     <Bar/>
  </Foo.Bars>
</Foo>
```

`Foo.Bars` collection will be empty. No exception will be thrown.

**Comment by jogibear9988** [comment]
From where should it know that it should be a collection? I would expect that It would deserialize as one "Bar" object

**Comment by cwensley** [comment]
Hm, do we know if System.Xaml works in this case?

You might be able to subclass XamlSchemaContext/XamlType to get this behaviour for known types/properties, but I haven't looked into it thus far.

**Comment by kekekeks** [comment]
`System.Xaml.XamlObjectWriterException: 'Cannot set unknown member 'Sandbox.Foo.Bars'.'`

I guess it would be OK to throw exception in this case then.

**Comment by cm4ker** [comment]
I have check this. 

```csharp
var xaml =
@"
<Foo xmlns='clr-namespace:MonoTests.Portable.Xaml;assembly=Portable.Xaml_test_net_4_0'>
	<Foo.Bars>
      <Bar/>
	</Foo.Bars>
</Foo>";

var r = GetReaderText(xaml);
var writer = new XamlObjectWriter(new XamlSchemaContext());
XamlServices.Transform(r, writer);
var res = writer.Result;
```
Portable.Xaml
![image](https://user-images.githubusercontent.com/5909124/46335576-b5cfb200-c649-11e8-80aa-25ad77890569.png)

System.Xaml
![image](https://user-images.githubusercontent.com/5909124/46335608-ced86300-c649-11e8-9260-f8e28a972c64.png)


For now the System.Xaml and Portable.Xaml have a same behavour. Do we need different?

**Comment by grokys** [comment]
From what I can see, System.Xaml has the same behavior. This can be overridden in the schema if necessary. I think we should close this.
