### ISSUE TITLE
Support `DependsOnAttribute`

### ISSUE THREAD

**Issue by grokys** [cwensley/Portable.Xaml#72]
As far as I can see, `DependsOnAttribute` isn't yet supported in Portable.Xaml.

**Comment by cm4ker** [comment]
Can you more detailed explain the problem? Or add failing tests and I'll fix this.

**Comment by grokys** [comment]
I'll create a PR with failing tests for this.

**Comment by grokys** [comment]
I tried to write a test for this, but I couldn't get it working in System.Xaml either. I don't know if this property just doesn't work, or whether I'm doing something wrong...

**Comment by cm4ker** [comment]
This attribute work only then we exec method "Save" i.e. then we serialize the object.

I think I can implement this.

Know more about how the DependsOnAttribute works from [this](https://docs.microsoft.com/en-us/dotnet/api/system.windows.markup.dependsonattribute?view=netframework-4.7.2) article.

**UPDATE:**
This is implement as a part of the PresentationFramework.dll.
https://docs.microsoft.com/en-us/dotnet/api/system.windows.markup.xamlwriter.save?view=netframework-4.5.2

This is not a task of the System.Xaml. => this is a bad place for implement this function. I think we can close this. Reopen it if you think that this issues need to discuss more.
