### ISSUE TITLE
Parsed invalid Xaml without throwing an exception

### ISSUE THREAD

**Issue by danwalmsley** [cwensley/Portable.Xaml#74]
I had the following code:

`<previewer:AvaloniaPreviewer Xaml="{Binding SourceText}" SourceFile={Binding SourceFile}" />`

Portable.Xaml parsed it without an issue. Notice missing " after SourceFile=

**Comment by cm4ker** [comment]
@danwalmsley, Hi there! Can you add repro? I can't reproduce this.

**Comment by danwalmsley** [comment]
It now throws an exception so I assume it got fixed along the way :)
