### ISSUE TITLE
Regression: Attached properties from non-default namespaces don't work

### ISSUE THREAD

**Issue by kekekeks** [cwensley/Portable.Xaml#75]
```xml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:a="clr-namespace:Avalonia.Controls;assembly=Avalonia.Controls">
  <StackPanel a:DockPanel.Dock="Left">
  </StackPanel>
</UserControl>
```

Portable.Xaml generates an unknown member here: https://github.com/cwensley/Portable.Xaml/blob/develop/src/Portable.Xaml/Portable.Xaml/XamlXmlReader.cs#L548 and doesn't add the attribute, so `ProcessAttributesToMember` doesn't see it and doesn't generate an attached member. XamlMember being unknown causes a crash in xaml writer later.

As a quick fix I've changed it like this: https://github.com/AvaloniaUI/Portable.Xaml/commit/d50ae8335eb50d4b9606de6f5fa1cbbc78bfd72f

**Comment by cwensley** [comment]
Hey, thanks again for reporting the issue!  This should now be fixed with #82.

Your quick fix causes the following tests to fail (which is what caused the regression to begin with), so I opted to only allow it when the name has a '.', meaning it's an attachable property.
```
MonoTests.Portable.Xaml.XamlObjectWriterTest.Read_InvalidPropertiesShouldThrowException
MonoTests.Portable.Xaml.XamlXmlReaderTest.Read_InvalidPropertiesShouldBeRead2
```

Cheers!
Curtis.
