### ISSUE TITLE
Dates are not serialised in the same format as System.Xaml

### ISSUE THREAD

**Issue by Benrnz** [cwensley/Portable.Xaml#8]
Hi,
I've been using this package to help me convert a library that uses XamlServices to serialise data into XAML.  I've noticed that when loading XAML serialised with System.Xaml dates have been formated using the ISO 8601 date format (aka "o" date format in c#).  Where as Portable.Xaml is serialising using an invariant or US date format.  

I want to get your feedback on this before I work on a Pull Request.

More Detail:
When serialising `new DateTime(2015, 12, 30, 23, 50, 50, UtcKind.Utc)` using System.Xaml.XamlServices,Save :
`<MyDto TheDateAndTime="2015-12-31T23:50:50Z" xmlns="clr-namespace:Portable.Xaml.UnitTest;assembly=Portable.Xaml.UnitTest" />`

And serialising `new DateTime(2015, 12, 30, 23, 50, 50, UtcKind.Local)` using System.Xaml.XamlServices.Save :
`<MyDto TheDateAndTime="2015-12-31T23:50:50+13:00" xmlns="clr-namespace:Portable.Xaml.UnitTest;assembly=Portable.Xaml.UnitTest" />`

With Portable.Xaml both cases are serialised to:
`<MyDto TheDateAndTime="12/31/2015 23:50:50" xmlns="clr-namespace:Portable.Xaml.UnitTest;assembly=Portable.Xaml.UnitTest" />`

Cheers, and keep up the good work!
Ben

**Comment by Benrnz** [comment]
My suggested fix would be to replicate the behaviour of System.Xaml in this case (I know your documentation does say the intention is to not necessarily replicate the behaviour exactly).

**Comment by cwensley** [comment]
Hi @Benrnz, thanks for reporting the issue!

Even though I don't intend the behaviour to be exact, it is more that Portable.Xaml might provide more features than System.Xaml.  For existing functionality such as this, I think it'd be ideal if Portable.Xaml matches it more closely.

Currently I am only focusing on deserialization of xaml, so contributions for serialization are very welcome.

**Comment by Benrnz** [comment]
Thanks for the fast response. I'll take a look at it over the next couple of days. 

Cheers

**Comment by Benrnz** [comment]
Hey @cwensley 
I've dug into this a little today, and I've found the unit test file that contains many other similar tests.  `MonoTests.Portable.Xaml.XamlXmlWriterTest`. However I'm confused by the way these tests are setup.  It appears they are testing the `System.Xaml.XamlServices` static class, shouldn't these tests be calling `Portable.Xaml.XamlServices`?

Is there some special setup I'm missing?

Cheers

**Comment by Benrnz** [comment]
Nevermind, I've just figured it out.  The three unit test projects are all using the same linked files, and I've been running the tests from the 4.5 project which invokes System.Xaml, but the Portable.Xaml-tests-pcl259 invokes Portable.Xaml. 

Cheers
