### ISSUE TITLE
Object type and MarkupExtension with conflicting names.

### ISSUE THREAD

**Issue by DevJohnC** [cwensley/Portable.Xaml#89]
When you have a graph object and `MarkupExtension` that share a name (but distinct type names) Portable.Xaml attempts to cast markup extension parameters to the graph object's type.

Take these classes:
```
class Report { ... }

[MarkupExtensionReturnType(typeof(object))]
class ReportExtension : MarkupExtension { ... }
```

and this XAML:

```
<Report xmlns="https://reports/project">
    <Button Target="{Report AnotherReport}" Label="Go To AnotherReport" />
</Report>
```

It's expected that Portable.Xaml will choose `ReportExtension` to create the `Target` property because it has a more specific type name (it has the `Extension` suffix) and derives from `MarkupExtension`. Instead, Portable.Xaml attempts to cast the string `"AnotherReport"` to the `Report` type.

**Comment by cwensley** [comment]
Thanks for the report!

Afaik, name resolution tries to use the non-suffixed name first so you may need to change one of those or use ReportExtension in the xaml.  It'd be interesting to see if System.Xaml behaves the same way.

**Comment by cm4ker** [comment]
@DevJohnC, hi there! Can you share example with behavour reproduction?

**Comment by cm4ker** [comment]
Seems it has been fixed.

```csharp
public class Report
{
	public object Target { get; set; }
}

[MarkupExtensionReturnType(typeof(object))]
public class ReportExtension : MarkupExtension
{
	private readonly object _key;
	public ReportExtension(object key)
	{
		_key = key;
	}

	public override object ProvideValue(IServiceProvider serviceProvider)
	{
		return _key;
	}
}

[Test]
public void TestExtensionNameCollision()
{
		var xaml = @"<Report xmlns='clr-namespace:MonoTests.Portable.Xaml;assembly=Portable.Xaml_test_net_4_0' 
Target='{Report AnotherReport}'></Report>".UpdateXml();
			var value = (Report)XamlServices.Parse(xaml);
			Assert.AreEqual("AnotherReport", value.Target);
}
```

This code is passed at the Portable.Xaml and System.Xaml feel free  to reopen the issue if problem remains.
