### ISSUE TITLE
x:Static can't resolve internal types

### ISSUE THREAD

**Issue by wjk** [cwensley/Portable.Xaml#93]
The title really says it all. The member being resolved can be non-public, but the type itself must be public or `{x:Static}` will not be able to find it. (I'm using version 0.21.0.) Could this please be rectified? Thanks!

**Comment by cm4ker** [comment]
Hi! Can you add failing test or code for reproduce the problem.

**Comment by cm4ker** [comment]
Anyway. The title says: "x:Static can't resolve internal types". Portable.Xaml as a System.Xaml can't access to the internal types. 

Then the reflection scan the properties(this how portable.xaml deside about property handling) it looks on the ```XamlMember.LookupIsReadPublic``` and ```XamlMember.LookupWritePublic``` (```XamlType``` works the same). 

If you want change the behavor you can create you own implementation of the XamlMember or the XamlType and override this. 

I'm closing this issue. Feel free to reopen  it if you have more questions about this.

Regards.
